version: "3.1"
services:
  
  cqhttp:
    image: richardchien/cqhttp:latest
    restart: always
    ports:
      - "9000:9000"  # the website access port
      - "5700:5700"  # http_api port, don't change it better
    volumes:
      - $PWD/coolq:/home/user/coolq # don't change it/
    networks:
      - app_net-cqhttp
    environment:
      - VNC_PASSWD=password # your website password
      - COOLQ_ACCOUNT=123456789 # your qq account
      - CQHTTP_WS_REVERSE_API_URL=ws://host.docker.internal:8080/ws/api/
      - CQHTTP_WS_REVERSE_EVENT_URL = ws://host.docker.internal:8080/ws/event/

    container_name: cqhttp
  
  
networks:
  app_net-cqhttp:
    driver: bridge